version: "3.8"

services:
  ms-event-manager:
    build:
      context: ./ms-event-manager
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: "mongodb+srv://lipem61:GRa3vbW0jPh3UNAL@desafiocompass.rip2j.mongodb.net/?retryWrites=true&w=majority&appName=desafiocompass"
    depends_on:
      - ms-ticket-manager
  
  ms-ticket-manager:
    build:
      context: ./ms-ticket-manager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: "mongodb+srv://lipem61:GRa3vbW0jPh3UNAL@desafiocompass.rip2j.mongodb.net/?retryWrites=true&w=majority&appName=desafiocompass"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

