spring.application.name=ms-ticket-manager

spring.data.mongodb.uri=mongodb://localhost:27017/ticketdb
spring.data.mongodb.database=ticketdb

feign.client.config.ms-event-manager.url=http://localhost:8082/eventmanagement/v1

server.port=8081

logging.level.org.springframework.web=DEBUG
logging.level.com.compassuol.ms_ticket_manager=DEBUG

# Actuator Configuration
management.endpoints.web.exposure.include=health,info

feign.client.config.ms-event-manager.loggerLevel=full

