spring.application.name=ms-ticket-manager

spring.data.mongodb.uri=mongodb://localhost:27017/event_ticket_db
spring.data.mongodb.database=event_ticket_db

feign.client.config.ms-event-manager.url=http://localhost:8082/eventmanagement/v1

server.port=8081

logging.level.org.springframework.web=DEBUG
logging.level.com.compassuol.ms_ticket_manager=DEBUG

# Actuator Configuration
management.endpoints.web.exposure.include=health,info

feign.client.config.ms-event-manager.loggerLevel=full

logging.level.com.compassuol.ms_ticket_manager.client.EventManagerClient=DEBUG

spring.jmx.enabled=false

spring.rabbitmq.host=possum.lmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=cgwulzjr
spring.rabbitmq.password=X3Px8I62sLXRqqb92MyKjd3EVcw9g11E
spring.rabbitmq.virtual-host=cgwulzjr

spring.mail.host=smtp.gmail.com
spring.mail.username=lipem61@gmail.com
spring.mail.password=bkdv yyec ciqv wdkv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.port=587


