spring.application.name=ms-ticket-manager

server.port=8081

feign.client.config.default.connectTimeout=5000
feign.client.config.default.readTimeout=5000

event-manager.service.url=http://localhost:8082

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
