spring.application.name=ms-event-manager

spring.cloud.openfeign.enabled=true

spring.main.allow-bean-definition-overriding=true

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=event_ticket_db

server.port=8082

spring.jmx.enabled=false

